services:
  kindwrind:
    image: binbashing/kindwrind:${TAG_OVERRIDE:-latest}
    container_name: kindwrind
    privileged: true
    ports:
      - 6443:6443
      - 5000:5000
    volumes:
      - ${KUBECONFIG:-~/.kube/config}:/kubeconfig/config
    environment:
      - KUBERNETES_VERSION
