name: KinDwRinD Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      trigger_reason:
        description: 'Reason for manual test trigger'
        required: false
        default: 'Manual trigger'

jobs:
  test-kindwrind:
    name: Test KinDwRinD Functionality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version information
        id: version
        run: |
          # Read KinD version from VERSION file - it must exist
          if [ -f VERSION ]; then
            KIND_VERSION=$(cat VERSION)
          else
            echo "ERROR: VERSION file not found!"
            exit 1
          fi
          echo "kind_version=${KIND_VERSION}" >> $GITHUB_OUTPUT
          echo "Using KinD version: ${KIND_VERSION}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build KinDwRinD image
        run: |
          docker build \
            --build-arg KIND_VERSION=${{ steps.version.outputs.kind_version }} \
            -t kindwrind-test .
      
      - name: Verify Docker command starts properly
        run: |
          # Test that the direct Docker command starts correctly
          docker run -d \
            --privileged \
            --name kindwrind-direct \
            -p 6444:6443 \
            -p 5001:5000 \
            -v /tmp/kube-direct:/kubeconfig \
            kindwrind-test
          
          # Wait briefly and check container is running
          sleep 10
          if ! docker ps | grep -q kindwrind-direct; then
            echo "Error: Direct Docker container failed to start"
            docker logs kindwrind-direct
            exit 1
          fi
          echo "Docker command approach verified"
          docker stop kindwrind-direct

      - name: Run using Docker Compose for full testing
        run: |
          # Modify the docker-compose.yml to use the local build
          sed -i 's|image: binbashing/kindwrind|image: kindwrind-test|' docker-compose.yml
          
          # Modify volume mount for testing
          sed -i 's|~/.kube:/kubeconfig|/tmp/kube-compose:/kubeconfig|' docker-compose.yml
          
          # Start with docker compose
          docker compose up -d

      - name: Wait for Kubernetes cluster (90s)
        run: |
          echo "Waiting for Kubernetes cluster to be ready..."
          count=0
          while [ $count -lt 90 ]; do
            sleep 1
            if docker exec kindwrind kubectl get nodes 2>/dev/null | grep -q "Ready"; then
              echo "Kubernetes cluster is ready!"
              break
            fi
            count=$((count+1))
            if [ $((count % 10)) -eq 0 ]; then
              echo "Still waiting... ($count/90s)"
            fi
          done
          
          if [ $count -eq 90 ]; then
            echo "Timeout waiting for Kubernetes cluster"
            docker logs kindwrind
            exit 1
          fi

      - name: Test registry functionality
        run: |
          # Pull a test image
          docker pull nginx:alpine
          
          # Tag for local registry
          docker tag nginx:alpine localhost:5000/nginx-test:latest
          
          # Push to local registry
          docker push localhost:5000/nginx-test:latest
          
          # Create deployment using the image from local registry
          docker exec kindwrind kubectl create deployment test-nginx --image=localhost:5000/nginx-test:latest
          
          # Wait for deployment to be ready
          count=0
          while [ $count -lt 60 ]; do
            sleep 1
            if docker exec kindwrind kubectl get deployment test-nginx 2>/dev/null | grep -q "1/1"; then
              echo "Deployment is ready!"
              break
            fi
            count=$((count+1))
            if [ $((count % 10)) -eq 0 ]; then
              echo "Waiting for deployment... ($count/60s)"
            fi
          done
          
          if [ $count -eq 60 ]; then
            echo "Deployment failed"
            docker exec kindwrind kubectl describe deployment test-nginx
            docker exec kindwrind kubectl describe pods -l app=test-nginx
            exit 1
          fi
          
          # Verify pod is running
          docker exec kindwrind kubectl get pods -l app=test-nginx -o wide

      - name: Test default Kubernetes version (current behavior)
        run: |
          # Check the current Kubernetes version (should be whatever KinD defaults to)
          K8S_VERSION=$(docker exec kindwrind kubectl version --client=false -o json | jq -r '.serverVersion.gitVersion')
          echo "✅ Default Kubernetes version: $K8S_VERSION"

      - name: Test custom Kubernetes version feature
        run: |
          # Stop current container
          docker compose down || true
          sleep 5
          
          # Test with a specific Kubernetes version (use a stable older version)
          CUSTOM_K8S_VERSION="v1.27.3"
          echo "Testing with custom Kubernetes version: $CUSTOM_K8S_VERSION"
          
          # Add KUBERNETES_VERSION environment variable to docker-compose.yml
          sed -i '/volumes:/i\        environment:' docker-compose.yml
          sed -i "/environment:/a\            - KUBERNETES_VERSION=$CUSTOM_K8S_VERSION" docker-compose.yml
          
          # Start with custom version
          docker compose up -d
          
          # Wait for cluster with custom version (longer timeout since it needs to pull image)
          echo "Waiting for custom Kubernetes cluster to be ready..."
          count=0
          while [ $count -lt 120 ]; do
            sleep 1
            if docker exec kindwrind kubectl get nodes 2>/dev/null | grep -q "Ready"; then
              echo "Custom Kubernetes cluster is ready!"
              break
            fi
            count=$((count+1))
            if [ $((count % 15)) -eq 0 ]; then
              echo "Still waiting for custom cluster... ($count/120s)"
            fi
          done
          
          if [ $count -eq 120 ]; then
            echo "Timeout waiting for custom Kubernetes cluster"
            docker logs kindwrind
            exit 1
          fi
          
          # Verify the custom version is actually being used
          ACTUAL_VERSION=$(docker exec kindwrind kubectl version --client=false -o json | jq -r '.serverVersion.gitVersion')
          echo "Actual Kubernetes version: $ACTUAL_VERSION"
          
          if [ "$ACTUAL_VERSION" = "$CUSTOM_K8S_VERSION" ]; then
            echo "✅ Custom Kubernetes version test passed!"
          else
            echo "❌ Custom Kubernetes version test failed!"
            echo "Expected: $CUSTOM_K8S_VERSION"
            echo "Actual: $ACTUAL_VERSION"
            exit 1
          fi
          
          # Quick functionality test with custom version
          docker exec kindwrind kubectl create deployment test-custom --image=nginx:alpine
          sleep 10
          if docker exec kindwrind kubectl get deployment test-custom 2>/dev/null | grep -q "1/1"; then
            echo "✅ Custom version deployment test passed!"
          else
            echo "❌ Custom version deployment test failed!"
            docker exec kindwrind kubectl describe deployment test-custom
            exit 1
          fi

      - name: Clean up
        if: always()
        run: |
          docker compose down || true