name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["kindwrind Integration Tests"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual build'
        required: false
        default: 'Manual trigger'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Only run if:
    # 1. Manually triggered via workflow_dispatch, OR
    # 2. Integration tests passed AND it was triggered by a push to main (not a PR), OR  
    # 3. Integration tests passed AND it was triggered by workflow_dispatch (automated update checks)
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.event == 'push' || github.event.workflow_run.event == 'workflow_dispatch')) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Read version information
        id: version
        run: |
          # Read Kind version from VERSION file
          KIND_VERSION=$(cat VERSION)
          echo "kind_version=${KIND_VERSION}" >> $GITHUB_OUTPUT
          echo "Kind version: ${KIND_VERSION}"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            binbashing/kindwrind:latest
            binbashing/kindwrind:v${{ steps.version.outputs.kind_version }}
            binbashing/kindwrind:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            KIND_VERSION=${{ steps.version.outputs.kind_version }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: binbashing/kindwrind
