name: Tag and Push Docker Image on Release

on:
  release:
    types: [published]

jobs:
  run-tests-first:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run KinDwRinD Integration Tests
        uses: ./.github/workflows/test.yml
        
  tag-and-push-on-release:
    runs-on: ubuntu-latest
    needs: run-tests-first
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git SHA for the Release Tag
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-list -n 1 ${{ github.event.release.tag_name }})"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create and push multi-arch Docker image
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled
          images=()
          for arch in amd64 arm64; do
            digest=$(docker manifest inspect binbashing/kindwrind:${{ steps.get_sha.outputs.sha }} | jq -r ".manifests[] | select(.platform.architecture==\"$arch\") | .digest")
            images+=("binbashing/kindwrind@$digest")
          done
          docker manifest create binbashing/kindwrind:${{ github.event.release.tag_name }} "${images[@]}"
          docker manifest push binbashing/kindwrind:${{ github.event.release.tag_name }}