name: Tag and Push Docker Image on Release

on:
  release:
    types: [published]

jobs:
  tag-and-push-on-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git SHA for the Release Tag
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-list -n 1 ${{ github.event.release.tag_name }})"

      - name: Pull Docker image matching Git SHA
        run: docker pull binbashing/kindwrind:${{ steps.get_sha.outputs.sha }}

      - name: Tag Docker image with Release Tag
        run: docker tag binbashing/kindwrind:${{ steps.get_sha.outputs.sha }} binbashing/kindwrind:${{ github.event.release.tag_name }}

      - name: Push tagged Docker image
        run: docker push binbashing/kindwrind:${{ github.event.release.tag_name }}
